reorganizer

diff --git a/bin/init b/bin/init
--- a/bin/init
+++ b/bin/init
@@ -9,8 +9,8 @@ def_appname=$(echo ${PWD##*/} | tr -d -c '[:alnum:]')
 
 while [[ ! $confirm == [yY] ]]; do
   warning=0
-  while [[ ! $appname =~ ^[a-zA-Z][a-zA-Z0-9]*$ ]]; do
-    if [[ $warning == 1 ]]; then echo -e "${RED}Error: App name must start with a letter and contain only letters & numbers${NC}"; fi
+  while [[ ! $appname ]]; do
+    if [[ $warning == 1 ]]; then echo -e "${RED}Error: App name must not be empty${NC}"; fi
     printf "What is the name of your app?\n"
     read -p "  [$def_appname]: " appname
     appname=${appname:-$def_appname}
@@ -41,9 +41,9 @@ directories=(${bundleid//./ })
 
 cd ios
 rm -rf ./*.xcodeproj
-cp -r ./Template/Boilerplate.xcodeproj ./$appname.xcodeproj
-LC_ALL=C find ./$appname.xcodeproj -type f -exec sed -i '' "s/Boilerplate/$appname/g" {} \;
-LC_ALL=C find ./$appname.xcodeproj -type f -exec sed -i '' "s/com.aino.boilerplate/$bundleid/g" {} \;
+cp -r ./Template/react-native-embryo.xcodeproj ./$appname.xcodeproj
+LC_ALL=C find ./$appname.xcodeproj -type f -exec sed -i '' "s/react-native-embryo/$appname/g" {} \;
+LC_ALL=C find ./$appname.xcodeproj -type f -exec sed -i '' "s/com.aino.embryo/$bundleid/g" {} \;
 cd ..
 printf "${GREEN}\xE2\x9C\x94 Xcode setup${NC}\n"
 
@@ -61,13 +61,13 @@ cd ../../../../../
 printf "${GREEN}\xE2\x9C\x94 Android setup${NC}\n"
 
 mkdir -p ~/.gradle
-if ! grep -q "BOILERPLATE" ~/.gradle/gradle.properties
+if ! grep -q "EMBRYO" ~/.gradle/gradle.properties
 then
-  printf "\n\nBOILERPLATE_RELEASE_STORE_FILE=boilerplate.keystore" >> ~/.gradle/gradle.properties
-  printf "\nBOILERPLATE_RELEASE_KEY_ALIAS=boilerplate" >> ~/.gradle/gradle.properties
-  printf "\nBOILERPLATE_RELEASE_STORE_PASSWORD=123456" >> ~/.gradle/gradle.properties
-  printf "\nBOILERPLATE_RELEASE_KEY_PASSWORD=123456" >> ~/.gradle/gradle.properties
-  printf "\xE2\x9C\x94 Added boilerplate keystore\n"
+  printf "\n\nREACT_NATIVE_EMBRYO_RELEASE_STORE_FILE=react-native-embryo.keystore" >> ~/.gradle/gradle.properties
+  printf "\nREACT_NATIVE_EMBRYO_RELEASE_KEY_ALIAS=react-native-embryo" >> ~/.gradle/gradle.properties
+  printf "\nREACT_NATIVE_EMBRYO_RELEASE_STORE_PASSWORD=123456" >> ~/.gradle/gradle.properties
+  printf "\nREACT_NATIVE_EMBRYO_RELEASE_KEY_PASSWORD=123456" >> ~/.gradle/gradle.properties
+  printf "${GREEN}\xE2\x9C\x94 Added embryo keystore${NC}\n"
 fi
 
 sed -i '' "s/\"name\": \".*\"/\"name\": \"${appname}\"/" package.json
@@ -85,7 +85,7 @@ printf "${GREEN}\xE2\x9C\x94 Set ENV to development${NC}\n"
 yarn run flow
 printf "${GREEN}\xE2\x9C\x94 Setup done!${NC}\n"
 
-if [ "$def_appname" != "app" ]; then
+if [ "${PWD##*/}" != "react-native-embryo" ]; then
   printf "\xF0\x9F\x8E\x97  ${GREEN}Don't forget to create a new git repo with 'git init'.${NC}\n"
   rm -rf ./.git
   # git init && git add . && git commit -m "First commit"
